/**
 * The Paradox of Progress
 * Generated by Riddle Finder Agent
 * Source: Original - Philosophical Theme
 * Date: 2025-12-05
 */

export const riddle = {
    id: 'the-paradox-of-progress',
    title: 'The Paradox of Progress',
    text: `The more you use me, the less I remain,
    Yet I am infinite and impossible to drain.
    I can solve any problem, unlock any door,
    But the more you discover, you realize there's more.
    
    I built civilizations, I toppled them too,
    I am the oldest and the newest truth.
    Freely given yet priceless to possess,
    What am I, this tool of progress?`,
    correctAnswers: [
    "knowledge",
    "information",
    "wisdom",
    "learning",
    "understanding"
],
    closeAnswers: [
    "education",
    "science",
    "intelligence",
    "data",
    "truth"
],
    hints: [
    "Think about something abstract and intellectual",
    "It grows as you share it",
    "It is the foundation of advancement",
    "Libraries and schools are built around it",
    "The more you have, the more you realize you need",
    "Socrates said he knew nothing except this"
],
    wrongAnswerFeedback: 'Think more abstractly - what powers all tools and solutions?',
    closeAnswerFeedback: 'Very close! What is the essence of these concepts?',
    explanation: 'Knowledge is infinite yet finite in any one person. It builds and destroys, and paradoxically, the more you learn, the more you realize how much you don\'t know.',
    answer: 'Knowledge'
};
